# Generated by Django 4.0.4 on 2022-06-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trainer_desc', models.CharField(max_length=200)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_app.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('courseImage', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_app.catagory')),
            ],
        ),
    ]
