# Generated by Django 4.0.4 on 2022-06-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0002_trainer_trainer_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=1000)),
            ],
        ),
    ]
