# Generated by Django 4.0.4 on 2022-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='person_img',
            field=models.ImageField(default=0, upload_to='testimonial'),
            preserve_default=False,
        ),
    ]
